<MainScreen>
    name : 'main'

    FloatLayout:
        size_hint: None,None


    DPEAButton:
        size: 100,100
        color: 0,0,1,1
        x: root.width *.5
        y: root.height *.5






    DPEAButton:
        size: 250, 100
        center_x: root.width * 0.25
        center_y: root.height * 0.75

        color: 0.035, 0.152, 0.725, 1
        text: "Shutdown"

        on_press: root.shutdown()